### ISSUE TITLE
'gulp prep' failing on new cloned repo

### ISSUE THREAD

**Issue by omefire** [Microsoft/TACO#143]
System: Ubuntu 14.04

Repro steps:
- git clone https://github.com/Microsoft/TACO.git
- cd TACO
- npm install gulp
- cd src
- gulp prep
- gulp

Expected results:
No errors.

Actual results:
omefire@omefire-Linux:~/Projects/Cordova/TACO-BIS/TACO$ cd src/
omefire@omefire-Linux:~/Projects/Cordova/TACO-BIS/TACO/src$ gulp prep
[15:01:03] Using gulpfile ~/Projects/Cordova/TACO-BIS/TACO/src/gulpfile.js
[15:01:03] Starting 'installDevDependencies'...
[15:01:28] Finished 'installDevDependencies' after 24 s
[15:01:28] Starting 'prep'...
[15:01:30] Finished 'prep' after 2.51 s
omefire@omefire-Linux:~/Projects/Cordova/TACO-BIS/TACO/src$ gulp
[15:01:43] Using gulpfile ~/Projects/Cordova/TACO-BIS/TACO/src/gulpfile.js
[15:01:43] Starting 'package'...
[15:01:43] Starting 'clean-templates'...
[15:01:43] Finished 'clean-templates' after 6.11 ms
[15:01:43] Starting 'prepare-templates'...
[15:01:44] Finished 'prepare-templates' after 411 ms
[15:01:44] Starting 'build'...
[15:01:44] Starting 'compile'...
[15:01:50] Finished 'compile' after 6.56 s
[15:01:50] Starting 'copy'...
[15:01:51] Finished 'copy' after 246 ms
[15:01:51] Finished 'build' after 6.81 s
[15:01:51] Starting 'copy'...
[15:01:51] Finished 'copy' after 210 ms
[15:01:51] Starting 'dev-package'...
[15:01:53] Finished 'dev-package' after 1.98 s
[15:01:53] Finished 'package' after 9.42 s
[15:01:53] Starting 'install-build'...
Installing /home/omefire/Projects/Cordova/TACO-BIS/TACO/build/packages/node_modules/taco-utils
Installing /home/omefire/Projects/Cordova/TACO-BIS/TACO/build/packages/node_modules/taco-kits
[15:02:02] 'install-build' errored after 9.49 s
[15:02:02] Error: Command failed: npm WARN package.json taco-kits@1.1.1-dev No README data
npm http GET https://registry.npmjs.org/taco-utils
npm http GET https://registry.npmjs.org/typescript/1.4.1
npm http 200 https://registry.npmjs.org/typescript/1.4.1
npm http GET https://registry.npmjs.org/typescript/-/typescript-1.4.1.tgz
npm http 200 https://registry.npmjs.org/taco-utils
npm ERR! notarget No compatible version found: taco-utils@'file:/home/omefire/Projects/Cordova/TACO-BIS/TACO/build/packages/node_modules/taco-utils.tgz'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.1.0-beta","1.1.0","1.1.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 3.16.0-50-generic
npm ERR! command "/home/omefire/.nvm/v0.10.25/bin/node" "/home/omefire/.nvm/v0.10.25/bin/npm" "install"
npm ERR! cwd /home/omefire/Projects/Cordova/TACO-BIS/TACO/build/packages/node_modules/taco-kits
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ETARGET
npm http 200 https://registry.npmjs.org/typescript/-/typescript-1.4.1.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/omefire/Projects/Cordova/TACO-BIS/TACO/build/packages/node_modules/taco-kits/npm-debug.log
npm ERR! not ok code 0

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
omefire@omefire-Linux:~/Projects/Cordova/TACO-BIS/TACO/src$ git branch
* master

**Comment by MSLaguana** [comment]
In order to build us, you need to use at least npm 2.X, and it seems that you have 1.3.24 there. 1.X doesn't support installing from local file paths

**Comment by meenakb** [comment]
Switching to NPM 2.11.3 on Ubuntu fixes the issue, closing this.
