### ISSUE TITLE
taco-livereload package build fails on Windows

### ISSUE THREAD

**Issue by teropes** [Microsoft/TACO#278]
Hello. I'm trying to install taco-cli on W7Pro x64, but the installation fails to taco-livereload build due to too long path / filename. I have already tried to reduce the path to minimum by setting my npm prefix config to just C:\npm as shown in the error log. How to get taco-cli installed clean without any build failures? Im running with the latest stable node.js release for Windows.

λ node -v
v4.4.0

λ npm -v
2.14.20

λ npm install -g taco-cli
...
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(399,5): error MSB3191: Unable to create directory "
Release\obj\validation\validation.tlog\". The specified path, file name, or both are too long. The fully qualified file name must be
less than 260 characters, and the directory name must be less than 248 characters. [C:\npm\node_modules\taco-cli\node_modules\taco-li
vereload\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\nod
e-gyp.js" "rebuild"
gyp ERR! cwd C:\npm\node_modules\taco-cli\node_modules\taco-livereload\node_modules\browser-sync\node_modules\socket.io\node_modules\s
ocket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
...

**Comment by teropes** [comment]
Understanding now bit more about the root cause of this issue, I decided to upgrade my npm to version 3. I was able to do clean installation of taco-cli with latest npm version 3.8.3 as it flattens the dependency tree and there are no longer too long paths.

Note to anyone else having this same issue: upgrading npm is easy with:
https://github.com/felixrieseberg/npm-windows-upgrade

Is there anything that can be done to support Windows taco-cli builds with npm 2? I find it bit odd that npm package developed by Microsoft does not build on Windows with latest stable Node.js and almost shortest possible path C:\npm\ ...
