### ISSUE TITLE
Cannot find module sax @ VSTS build agent

### ISSUE THREAD

**Issue by jsiegmund** [Microsoft/TACO#303]
The build agent for my Visual Studio Team Services tenant seems to have a cache problem or something like that. I switched to version 6.2.1-dev locally after which I got a compile error. Cleaned out the cache as suggested in the error message solved this, but after pushing the code to my repo, the same error now pops up in the online build. As there is no "Clean cache" button there, I'm left wondering what I need to do to fix this? 

Error is as follows:

> cordova@6.2.1-dev already installed.
Adding support plugin.
module.js:341
    throw err;
    ^
Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\cordova\node_modules\_cordova\lib\npm_cache\cordova-android\5.2.0-nightly.2016.6.9.81d62196\package\node_modules\elementtree\lib\parsers\sax.js:3:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
{ [Error: cmd: Command failed with exit code 1] code: 1 }

**Comment by MSLaguana** [comment]
The VSTS Cordova support is in a separate repo, could you please open this issue on https://github.com/Microsoft/vsts-cordova-tasks

**Comment by jsiegmund** [comment]
Ah ok, sorry about that!
